import demoJson from "./demo-generated.json"
import type { CapsulePayload } from "./capsule"

/** "The First Ark" — a real capsule sealed to a round that has already
 *  passed, with the round's real beacon recorded alongside it. It exists so
 *  anyone can watch the full verify-and-decrypt ritual — offline, before
 *  trusting a seal they cannot fast-forward. Generated by
 *  `npm run seal-demo`; null until that has been run. */
export const DEMO_CAPSULE: CapsulePayload | null = demoJson as CapsulePayload | null
